

CREATE DATABASE CRIPTOMONEDA
GO
USE CRIPTOMONEDA
GO
CREATE TABLE USUARIO
(
	[USUARIO] VARCHAR(20)NOT NULL,
	[CONTRA] VARCHAR(20) NOT NULL,
	CONSTRAINT [PK_USUARIO] PRIMARY KEY ([USUARIO]),
)	
GO
INSERT INTO USUARIO VALUES('ADMIN','123')
INSERT INTO USUARIO VALUES('BETA','123')


CREATE TABLE MONEDA
(
	[CODMONEDA] CHAR(4)NOT NULL,
	[DESCRIPCION] VARCHAR(50) NULL,
	[TIPOCAMBIO]DECIMAL(10,4) NULL,
	CONSTRAINT [PK_MONEDA] PRIMARY KEY ([CODMONEDA]) ,
)
GO

INSERT INTO MONEDA VALUES('BTC','BITCOIN',39500.50)
INSERT INTO MONEDA VALUES('OASI','ROSE',0.29)
INSERT INTO MONEDA VALUES('USDT','USDT',1)

GO
CREATE TABLE CLIENTE
(
	[IDCARTERA] INT NOT NULL,
	[FONDOS] DECIMAL(10,4) NULL,
	[CODMONEDA] CHAR(4)NOT NULL,
	[USUARIO] VARCHAR(20)NOT NULL,
	CONSTRAINT [FK_CLIENTE_USUARIO] FOREIGN KEY ([USUARIO]) REFERENCES USUARIO([USUARIO]),
)
GO
INSERT INTO CLIENTE VALUES(1,0,'BTC','ADMIN')
INSERT INTO CLIENTE VALUES(1,0,'OASI','ADMIN')
INSERT INTO CLIENTE VALUES(1,100,'USDT','ADMIN')

INSERT INTO CLIENTE VALUES(2,0,'BTC','BETA')
INSERT INTO CLIENTE VALUES(2,0,'OASI','BETA')
INSERT INTO CLIENTE VALUES(2,100,'USDT','BETA')

GO
CREATE TABLE HISTORIAL
(
	[ID] INT IDENTITY(1,1) NOT NULL,
	[IDCARTERA]INT NOT NULL,
	[CODMONEDA] CHAR(4)NOT NULL,
	[MONTO]DECIMAL(10,4) NULL,
	[TIPOTRANS] CHAR(1)NOT NULL,
	CONSTRAINT [FK_HISTORIAL_MONEDA] FOREIGN KEY ([CODMONEDA]) REFERENCES MONEDA([CODMONEDA]),
)
GO

