/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Clases.Cliente;
import Clases.Conexion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.util.ArrayList;

/**
 *
 * @author CAROLINA
 */
public final class JFormInterfaz extends javax.swing.JFrame {

    /**
     * Creates new form JFormInterfaz
     */
    private String Usuario = "";

    public JFormInterfaz(String eUsuario) {
        initComponents();
//        JFormLogin login = new JFormLogin();
        Usuario = eUsuario;
        mostrar();
        obtenerMontoCuentaUSDT();
        this.setLocationRelativeTo(null);

    }

    public void mostrar() {
        ArrayList<Cliente> Lista = new ArrayList<>();
        double total, usdt = 0, oasis = 0, btc = 0;
        Connection con = Conexion.getConexion();
        try {
            Statement stm = con.createStatement();

            ResultSet rs1 = stm.executeQuery("SELECT CODMONEDA,FONDOS FROM CLIENTE WHERE USUARIO ='" + Usuario + "'");
            while (rs1.next()) {
                Cliente item = new Cliente();
                item.setMoneda(rs1.getString(1));
                item.setFondos(rs1.getDouble(2));
                Lista.add(item);
                item = null;
            }
            for (Cliente cliente : Lista) {
                if (cliente.getMoneda().equals("BTC")) {
                    btc = cliente.getFondos();
                } else if (cliente.getMoneda().equals("USDT")) {
                    usdt = cliente.getFondos();

                } else if (cliente.getMoneda().equals("OASI")) {
                    oasis = cliente.getFondos();
                }
            }
            DecimalFormat df = new DecimalFormat("#0.0000");
            DecimalFormat df2 = new DecimalFormat("#0.00");
            lblusdt.setText("" + df.format(usdt));
            lblbtc.setText("" + df.format(btc));
            lbloasi.setText("" + df.format(oasis));
            total = usdt + btc + oasis;
            porusdt.setText(String.valueOf(df2.format((usdt / total) * 100)));
            porbtc.setText(String.valueOf(df2.format((btc / total) * 100)));
            poroasi.setText(String.valueOf(df2.format((oasis / total) * 100)));
            rs1.close();
            stm.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    void obtenerMontoCuentaUSDT() {
        Connection con = Conexion.getConexion();
        try {
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT cast(round(SUM(FONDOS*TIPOCAMBIO),2) as numeric(36,2))MONTO_USDT FROM CLIENTE CL\n"
                    + "INNER JOIN MONEDA MON ON CL.CODMONEDA=MON.CODMONEDA WHERE USUARIO='" + Usuario + "'");

            while (rs.next()) {
                lblfondosusdt.setText(rs.getString("MONTO_USDT"));
            }
            rs.close();
            stmt.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//             */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblusdt = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        porusdt = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblfondosusdt = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblbtc = new javax.swing.JLabel();
        lbloasi = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        porbtc = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        poroasi = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        btnHistorial = new javax.swing.JButton();
        btnTranferencias = new javax.swing.JButton();
        btnRecargarFondos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblusdt.setText("0");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel2.setText("USDT");

        porusdt.setText("0");

        jLabel4.setText("BTC");

        jLabel5.setText("OASI");

        lblfondosusdt.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lblfondosusdt.setText("0.0");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Account");

        jLabel10.setText("0xABFF4cF0E4D092dA4b9E97C7BDDEE31198270EeB");

        jLabel11.setText("USDT");

        lblbtc.setText("0");

        lbloasi.setText("0");

        jLabel16.setText("%");

        jLabel17.setText("%");

        porbtc.setText("0");

        jLabel19.setText("%");

        poroasi.setText("0");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel25.setText("Activos");

        btnHistorial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnHistorial.setText("Historial");

        btnTranferencias.setText("Tranferencias");
        btnTranferencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTranferenciasActionPerformed(evt);
            }
        });

        btnRecargarFondos.setText("Recargar Fondos(USDT)");
        btnRecargarFondos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecargarFondosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel11)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbloasi, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                            .addComponent(lblbtc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblusdt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(porusdt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(poroasi, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(porbtc, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17)))
                        .addGap(23, 23, 23))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(200, 200, 200))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblfondosusdt)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTranferencias)
                                .addGap(33, 33, 33)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRecargarFondos)
                            .addComponent(jLabel2))
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnHistorial)
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblfondosusdt)
                    .addComponent(jLabel2))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTranferencias)
                    .addComponent(btnRecargarFondos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel25)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblusdt)
                    .addComponent(porusdt)
                    .addComponent(jLabel11)
                    .addComponent(jLabel16))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblbtc)
                    .addComponent(porbtc)
                    .addComponent(jLabel17))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lbloasi)
                    .addComponent(poroasi)
                    .addComponent(jLabel19))
                .addGap(87, 87, 87)
                .addComponent(btnHistorial)
                .addGap(68, 68, 68))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTranferenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTranferenciasActionPerformed

        Tranferencias trans = new Tranferencias();
        trans.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTranferenciasActionPerformed

    private void btnRecargarFondosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecargarFondosActionPerformed
        RecargaFondos trans = new RecargaFondos();
        trans.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRecargarFondosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFormInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFormInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFormInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFormInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new JFormInterfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHistorial;
    private javax.swing.JButton btnRecargarFondos;
    private javax.swing.JButton btnTranferencias;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblbtc;
    private javax.swing.JLabel lblfondosusdt;
    private javax.swing.JLabel lbloasi;
    private javax.swing.JLabel lblusdt;
    private javax.swing.JLabel porbtc;
    private javax.swing.JLabel poroasi;
    private javax.swing.JLabel porusdt;
    // End of variables declaration//GEN-END:variables
}
